// Anedot outbound webhook handler.
//
// Receives donation events from Anedot, verifies HMAC-SHA256 signature against
// the raw request body, persists a canonical donation row to Upstash Redis, sends
// the donor receipt + treasurer notification via Resend, and (during the late-cycle
// window) fires the Mississippi 48-Hour Report alerter per Miss. Code Ann. § 23-15-807(f).
//
// FEATURE FLAG: this route returns 501 Not Implemented until ANEDOT_WEBHOOK_SECRET
// is set in environment. That keeps it safely deployable before cutover.

import { NextResponse } from "next/server";
import { createHmac, timingSafeEqual } from "crypto";
import { Redis } from "@upstash/redis";
import { getResend } from "@/lib/resend";
import { render } from "@react-email/render";
import DonorReceipt from "@/emails/DonorReceipt";
import DonorNotification from "@/emails/DonorNotification";

// Redis keys (kept consistent with the existing /api/webhooks/stripe handler).
const KV_KEY_DONOR_COUNT = "rcc4judge:donor_count";
const KV_KEY_DONATIONS = "rcc4judge:donations";
const KV_KEY_PROCESSED_EVENTS = "rcc4judge:anedot:processed_events";
const KV_TTL_PROCESSED_EVENT_SECONDS = 60 * 60 * 24 * 90; // 90 days

// Anedot webhook signature: HMAC-SHA256 of raw body, hex-encoded, sent as plain
// hex (no `sha256=` prefix) in the `x-request-signature` header.
const ANEDOT_SIGNATURE_HEADER = "x-request-signature";
const ANEDOT_SIGNATURE_ALGO = "sha256" as const;

// Identity constants — used to verify each webhook came from the right account
// and was generated by one of our two donation forms. Defense in depth on top of
// HMAC: even if an attacker forged a valid signature, the payload still has to
// claim to belong to our account.
const ANEDOT_ACCOUNT_UID = "ae1527c960d1efccf7eb2";
const ANEDOT_INDIVIDUAL_PAGE_ID = "065d10de-39ae-4cec-8717-cbdc5460ad86";
const ANEDOT_CORP_PAGE_ID = "fbe5a8d9-e2a9-41eb-a99c-a1ad531afcb1";

// Mississippi 48-Hour Report window per Miss. Code Ann. § 23-15-807(f):
// any contribution > $200 received after the 10th day before the election
// but more than 48 hours before 12:01 a.m. on Election Day must be reported
// to the SOS within 48 hours of receipt. Election Day: November 3, 2026.
const FORTY_EIGHT_HOUR_WINDOW_START = new Date("2026-10-23T05:00:00.000Z"); // 00:00 CDT
const FORTY_EIGHT_HOUR_WINDOW_END = new Date("2026-11-01T05:01:00.000Z");
const FORTY_EIGHT_HOUR_AMOUNT_THRESHOLD_CENTS = 20000;

type DonorType =
  | "individual"
  | "corporation"
  | "other";

type DonationStatus =
  | "succeeded"
  | "pending"
  | "failed"
  | "refunded"
  | "partially_refunded"
  | "voided"
  | "chargeback"
  | "chargeback_reversed"
  | "ach_returned"
  | "settled";

interface AnedotDonationRow {
  // Anedot reconciliation
  anedot_donation_id: string;
  anedot_submission_id: string;
  anedot_account_uid: string;
  anedot_action_page_id: string;
  anedot_action_page_name: string;
  webhook_event_id: string;
  webhook_event_type: string;

  // Identification (Miss. Code Ann. § 23-15-801(g))
  donor_type: DonorType;
  first_name: string;
  last_name: string;
  middle_name: string;
  entity_name: string;
  occupation: string;
  employer: string;
  authorized_signer_title: string;

  // Address
  address_street: string;
  address_street_2: string;
  address_city: string;
  address_state: string;
  address_zip: string;
  address_country: string;

  // Contact
  email: string;
  phone: string;

  // Attestation note: the form-level Requirement field enforces the donor
  // attestation. Anedot does not include attestation status in webhook payloads —
  // delivery of this webhook implies the donor satisfied form requirements.
  attestation_text_version: string;

  // Transaction
  amount_cents: number;
  net_amount_cents: number;
  fee_cents: number;
  currency: string;
  recurring: boolean;
  recurring_interval: string;
  payment_method: string;
  card_type: string;
  card_last4: string;
  status: DonationStatus;
  is_in_kind: boolean;

  // Time
  donated_at: string;
  received_at: string;

  // Audit / attribution
  ip_address: string;
  user_agent: string;
  utm_source: string;
  utm_medium: string;
  utm_campaign: string;
  utm_content: string;
  utm_term: string;

  // Raw audit
  raw_payload: unknown;
}

function getRedis(): Redis | null {
  const url = process.env.KV_REST_API_URL;
  const token = process.env.KV_REST_API_TOKEN;
  if (!url || !token) return null;
  return new Redis({ url, token });
}

function verifyAnedotSignature(
  rawBody: string,
  signatureHeader: string | null,
  secret: string,
): boolean {
  if (!signatureHeader) return false;

  const expectedHex = createHmac(ANEDOT_SIGNATURE_ALGO, secret)
    .update(rawBody)
    .digest("hex");

  // Anedot sends the signature as plain hex (no "sha256=" prefix).
  const providedHex = signatureHeader.trim();

  if (expectedHex.length !== providedHex.length) return false;

  try {
    return timingSafeEqual(
      Buffer.from(expectedHex, "hex"),
      Buffer.from(providedHex, "hex"),
    );
  } catch {
    return false;
  }
}

function parseDollarsToCents(value: unknown): number {
  if (typeof value === "number") return Math.round(value * 100);
  if (typeof value !== "string") return 0;
  const parsed = parseFloat(value);
  if (Number.isNaN(parsed)) return 0;
  return Math.round(parsed * 100);
}

function pickString(value: unknown): string {
  if (typeof value !== "string") return "";
  return value;
}

function parseBooleanString(value: unknown): boolean {
  if (typeof value === "boolean") return value;
  if (typeof value === "string") return value.toLowerCase() === "true";
  return false;
}

function inferDonorType(actionPageId: string): DonorType {
  if (actionPageId === ANEDOT_INDIVIDUAL_PAGE_ID) return "individual";
  if (actionPageId === ANEDOT_CORP_PAGE_ID) return "corporation";
  return "other";
}

function mapEventToStatus(eventType: string): DonationStatus {
  switch (eventType) {
    case "donation_completed":
      return "succeeded";
    case "donation_settled":
      return "settled";
    case "donation_refunded":
      return "refunded";
    case "donation_partially_refunded":
      return "partially_refunded";
    case "donation_voided":
      return "voided";
    case "donation_chargeback":
      return "chargeback";
    case "donation_chargeback_reversed":
      return "chargeback_reversed";
    case "donation_ach_returned":
      return "ach_returned";
    case "commitment_failed_to_process":
      return "failed";
    case "commitment_created":
    case "commitment_updated":
    default:
      return "pending";
  }
}

function mapAnedotPayload(
  envelope: Record<string, unknown>,
  webhookEventId: string,
  webhookEventType: string,
  userAgent: string,
): AnedotDonationRow | null {
  const payload = envelope.payload as Record<string, unknown> | undefined;
  if (!payload) return null;

  // Defense in depth: reject payloads that don't claim to belong to our account.
  const accountUid = pickString(payload.account_uid);
  if (accountUid && accountUid !== ANEDOT_ACCOUNT_UID) {
    console.warn(
      "[anedot webhook] rejecting payload from unexpected account",
      { accountUid, expected: ANEDOT_ACCOUNT_UID },
    );
    return null;
  }

  const actionPageId = pickString(payload.action_page_id);
  const donorType = inferDonorType(actionPageId);

  const donation = payload.donation as Record<string, unknown> | undefined;
  const fees = donation?.fees as Record<string, unknown> | undefined;
  const anedotFees = fees?.anedot_fees as Record<string, unknown> | undefined;

  const amountCents = parseDollarsToCents(
    payload.amount_in_dollars ?? payload.event_amount ?? payload.total_amount_in_dollars,
  );
  const netAmountCents = parseDollarsToCents(payload.net_amount);
  const feeCents = parseDollarsToCents(anedotFees?.amount);

  const customFields =
    (payload.custom_field_responses as Record<string, unknown> | undefined) ?? {};

  // For corporate donations, the Entity Name + Authorized Signer Title come
  // through as custom_field_responses. Field keys aren't known until the first
  // real corp donation; we extract by case-insensitive label match.
  const entityName = extractCustomField(customFields, [
    "corporation legal name",
    "entity legal name",
    "organization",
  ]) || pickString(payload.organization);
  const authorizedSignerTitle = extractCustomField(customFields, [
    "authorized signer title",
    "title",
  ]) || pickString(payload.title);

  const row: AnedotDonationRow = {
    anedot_donation_id:
      pickString(donation?.id) ||
      pickString(payload.id) ||
      pickString(payload.commitment_uid) ||
      "",
    anedot_submission_id: pickString(payload.submission_id),
    anedot_account_uid: accountUid,
    anedot_action_page_id: actionPageId,
    anedot_action_page_name: pickString(payload.action_page_name),
    webhook_event_id: webhookEventId,
    webhook_event_type: webhookEventType,

    donor_type: donorType,
    first_name: pickString(payload.first_name),
    last_name: pickString(payload.last_name),
    middle_name: pickString(payload.middle_name),
    entity_name: entityName,
    occupation: pickString(payload.occupation),
    employer: pickString(payload.employer_name),
    authorized_signer_title: authorizedSignerTitle,

    address_street: pickString(payload.address_line_1),
    address_street_2: pickString(payload.address_line_2),
    address_city: pickString(payload.address_city),
    address_state: pickString(payload.address_region),
    address_zip: pickString(payload.address_postal_code),
    address_country: pickString(payload.address_country),

    email: pickString(payload.email),
    phone: pickString(payload.phone),

    attestation_text_version: "v1-2026-05-08",

    amount_cents: amountCents,
    net_amount_cents: netAmountCents,
    fee_cents: feeCents,
    currency: "USD",
    recurring:
      parseBooleanString(payload.is_recurring_commitment) ||
      parseBooleanString(payload.recurring) ||
      pickString(payload.frequency) === "monthly",
    recurring_interval: pickString(payload.frequency),
    payment_method: pickString(payload.source) || pickString(payload.payment_description),
    card_type: pickString(donation?.card_type),
    card_last4: pickString(donation?.card_last_digits),
    status: mapEventToStatus(webhookEventType),
    is_in_kind: false,

    donated_at:
      pickString(payload.created_at_iso8601) ||
      pickString(payload.created_at) ||
      new Date().toISOString(),
    received_at: new Date().toISOString(),

    ip_address: pickString(payload.ip_address),
    user_agent: userAgent,
    utm_source: pickString(payload.utm_source),
    utm_medium: pickString(payload.utm_medium),
    utm_campaign: pickString(payload.utm_campaign),
    utm_content: pickString(payload.utm_content),
    utm_term: pickString(payload.utm_term),

    raw_payload: envelope,
  };

  return row;
}

function extractCustomField(
  customFields: Record<string, unknown>,
  candidateLabels: string[],
): string {
  for (const [key, value] of Object.entries(customFields)) {
    const keyLower = key.toLowerCase();
    if (candidateLabels.some((label) => keyLower.includes(label))) {
      if (typeof value === "string") return value;
      if (value && typeof value === "object" && "value" in value) {
        const v = (value as { value: unknown }).value;
        if (typeof v === "string") return v;
      }
    }
  }
  return "";
}

function isFortyEightHourReportRequired(
  amount_cents: number,
  received_at: Date,
): boolean {
  return (
    amount_cents > FORTY_EIGHT_HOUR_AMOUNT_THRESHOLD_CENTS &&
    received_at >= FORTY_EIGHT_HOUR_WINDOW_START &&
    received_at <= FORTY_EIGHT_HOUR_WINDOW_END
  );
}

async function fireFortyEightHourAlert(
  row: AnedotDonationRow,
): Promise<void> {
  const resend = getResend();
  const treasurerEmail =
    process.env.CAMPAIGN_DONATION_NOTIFY_EMAILS
      ?.split(",")
      .map((e) => e.trim())
      .find((e) => e.toLowerCase().startsWith("treasurer@")) ??
    "Treasurer@RCC4Judge.com";
  const fromAddress =
    process.env.CAMPAIGN_FROM_DONATE ?? "donate@rcc4judge.com";

  const dueBy = new Date(
    new Date(row.received_at).getTime() + 48 * 60 * 60 * 1000,
  );
  const donorIdentity = row.entity_name
    ? `${row.entity_name} (${row.donor_type})`
    : `${row.first_name} ${row.last_name} — ${row.occupation || "—"} at ${row.employer || "—"}`;
  const formattedAmount = `$${(row.amount_cents / 100).toFixed(2)}`;

  await resend.emails.send({
    from: fromAddress,
    to: [treasurerEmail],
    subject: `[48-HOUR REPORT REQUIRED] ${formattedAmount} from ${row.first_name} ${row.last_name}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 640px; margin: 0 auto;">
        <div style="background-color: #b91c1c; padding: 20px 28px; border-radius: 0 0 8px 8px;">
          <p style="color: rgba(255,255,255,0.85); font-size: 11px; letter-spacing: 3px; text-transform: uppercase; margin: 0 0 4px;">
            Mississippi 48-Hour Report Required
          </p>
          <p style="color: #FFFFFF; font-size: 22px; font-weight: bold; margin: 0;">
            File within 48 hours of receipt
          </p>
        </div>
        <div style="background-color: #FFFFFF; border: 1px solid #EDE9DF; border-radius: 12px; padding: 24px 32px; margin: 24px 0;">
          <p style="margin: 0 0 16px; font-size: 14px;">
            Per <strong>Miss. Code Ann. § 23-15-807(f)</strong>, the following contribution must be
            reported to the Mississippi Secretary of State's Office, Elections Division, within 48 hours
            of receipt because it exceeds $200 and was received during the late-cycle window
            (between the 10th day before the election and 48 hours before Election Day).
          </p>
          <hr style="border: none; border-top: 1px solid #EDE9DF; margin: 16px 0;" />
          <p style="margin: 0 0 8px;"><strong>Donor:</strong> ${donorIdentity}</p>
          <p style="margin: 0 0 8px;"><strong>Address:</strong> ${row.address_street}, ${row.address_city}, ${row.address_state} ${row.address_zip}</p>
          <p style="margin: 0 0 8px;"><strong>Amount:</strong> ${formattedAmount}</p>
          <p style="margin: 0 0 8px;"><strong>Date received:</strong> ${row.received_at}</p>
          <p style="margin: 0 0 8px;"><strong>Payment method:</strong> ${row.payment_method}</p>
          <p style="margin: 0 0 8px;"><strong>In-kind?</strong> ${row.is_in_kind ? "Yes" : "No"}</p>
          <p style="margin: 0 0 8px;"><strong>Anedot reference:</strong> ${row.anedot_donation_id}</p>
          <hr style="border: none; border-top: 1px solid #EDE9DF; margin: 16px 0;" />
          <p style="margin: 0 0 8px; color: #b91c1c; font-weight: bold;">
            File by: ${dueBy.toISOString()}
          </p>
          <p style="margin: 0; font-size: 12px;">
            File via email to <a href="mailto:CampaignFinance@sos.ms.gov">CampaignFinance@sos.ms.gov</a>,
            fax to (601) 576-2545, or hand delivery to 401 Mississippi Street, Jackson, MS 39201.
            Use the Forty-Eight Hour Report form available at sos.ms.gov.
          </p>
        </div>
      </div>
    `,
  });
}

export async function POST(request: Request) {
  const secret = process.env.ANEDOT_WEBHOOK_SECRET;

  // Feature flag: route is inert until the secret is set.
  if (!secret) {
    return NextResponse.json(
      { error: "Anedot webhook handler not configured" },
      { status: 501 },
    );
  }

  const rawBody = await request.text();
  const signatureHeader = request.headers.get(ANEDOT_SIGNATURE_HEADER);

  if (!verifyAnedotSignature(rawBody, signatureHeader, secret)) {
    return NextResponse.json({ error: "Invalid signature" }, { status: 401 });
  }

  let envelope: Record<string, unknown>;
  try {
    envelope = JSON.parse(rawBody) as Record<string, unknown>;
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  // Anedot identifies events via two channels: the `event` field at the root
  // of the body, and the `x-integration-event` header. Prefer the body field
  // (authoritative) but fall back to the header for safety.
  const eventTypeFromBody = pickString(envelope.event);
  const eventTypeFromHeader = pickString(
    request.headers.get("x-integration-event"),
  );
  const webhookEventType = eventTypeFromBody || eventTypeFromHeader;

  // Idempotency key: x-request-id on the webhook itself. Real webhooks have
  // unique values; test pushes from Anedot use the literal "test-request-id".
  const webhookEventId =
    pickString(request.headers.get("x-request-id")) ||
    pickString(envelope.id) ||
    "";

  if (!webhookEventId || !webhookEventType) {
    return NextResponse.json(
      { error: "Missing event metadata" },
      { status: 400 },
    );
  }

  // Allow test pushes through to the mapper but skip persistence/email so we
  // don't pollute donor records with Anedot's "Gandalf Thegrey" fixture data.
  const isTestPush = webhookEventId === "test-request-id";

  // Idempotency check (real webhooks only).
  const redis = getRedis();
  if (redis && !isTestPush) {
    const alreadyProcessed = await redis.get<string>(
      `${KV_KEY_PROCESSED_EVENTS}:${webhookEventId}`,
    );
    if (alreadyProcessed) {
      return NextResponse.json({ received: true, idempotent: true });
    }
  }

  const row = mapAnedotPayload(
    envelope,
    webhookEventId,
    webhookEventType,
    pickString(request.headers.get("user-agent")),
  );

  if (!row) {
    console.warn(
      "[anedot webhook] mapper returned null — payload not mappable",
      { webhookEventId, webhookEventType },
    );
    return NextResponse.json({ received: true, mapped: false });
  }

  // Test pushes: acknowledge, log, do not persist or email.
  if (isTestPush) {
    console.log("[anedot webhook] test push acknowledged", {
      webhookEventType,
      anedot_donation_id: row.anedot_donation_id,
      amount_cents: row.amount_cents,
    });
    return NextResponse.json({ received: true, test: true });
  }

  // Persist real donation events.
  if (redis) {
    await Promise.all([
      redis.lpush(KV_KEY_DONATIONS, JSON.stringify(row)),
      redis.set(
        `${KV_KEY_PROCESSED_EVENTS}:${webhookEventId}`,
        "1",
        { ex: KV_TTL_PROCESSED_EVENT_SECONDS },
      ),
      // Only increment donor count on the success event.
      row.status === "succeeded" || row.status === "settled"
        ? redis.incr(KV_KEY_DONOR_COUNT)
        : Promise.resolve(),
    ]);
  }

  // 48-Hour Report alerter — only on success events in the late-cycle window.
  if (row.status === "succeeded" || row.status === "settled") {
    const receivedAt = new Date(row.received_at);
    if (isFortyEightHourReportRequired(row.amount_cents, receivedAt)) {
      try {
        await fireFortyEightHourAlert(row);
      } catch (err) {
        console.error("[anedot webhook] 48-hour alert failed", err);
      }
    }
  }

  // Donor receipt + treasurer notification on success only.
  if (row.status === "succeeded") {
    try {
      const resend = getResend();
      const fromAddress =
        process.env.CAMPAIGN_FROM_DONATE ?? "donate@rcc4judge.com";
      const notifyEmails = (
        process.env.CAMPAIGN_DONATION_NOTIFY_EMAILS ?? ""
      )
        .split(",")
        .map((e) => e.trim())
        .filter(Boolean);

      const donorName = row.entity_name
        ? row.entity_name
        : `${row.first_name} ${row.last_name}`.trim();
      const amountDollars = Math.round(row.amount_cents / 100);
      const contributorTypeForReceipt: "individual" | "corporate" =
        row.donor_type === "individual" ? "individual" : "corporate";

      const receiptHtml = await render(
        DonorReceipt({
          donorName,
          amount: amountDollars,
          tierName: "Custom",
          isRecurring: row.recurring,
          contributorType: contributorTypeForReceipt,
          transactionDate: row.donated_at,
          transactionId: row.anedot_donation_id,
        }),
      );

      const notificationHtml = await render(
        DonorNotification({
          donorName,
          donorEmail: row.email,
          donorPhone: row.phone,
          amount: amountDollars,
          tierName: "Custom",
          isRecurring: row.recurring,
          contributorType: contributorTypeForReceipt,
          address: `${row.address_street}, ${row.address_city}, ${row.address_state} ${row.address_zip}`,
          employer: row.employer,
          occupation: row.occupation,
          corporateName: row.entity_name,
          corporateAuthorizer: row.authorized_signer_title,
          transactionId: row.anedot_donation_id,
          transactionDate: row.donated_at,
        }),
      );

      const emailPromises: Promise<unknown>[] = [];

      if (row.email) {
        emailPromises.push(
          resend.emails.send({
            from: fromAddress,
            to: [row.email],
            replyTo:
              process.env.CAMPAIGN_REPLY_TO ?? "Treasurer@RCC4Judge.com",
            subject: `Thank you for your ${row.recurring ? "monthly " : ""}contribution to the Committee to Elect Rhonda C. Cooper`,
            html: receiptHtml,
          }),
        );
      }

      if (notifyEmails.length > 0) {
        emailPromises.push(
          resend.emails.send({
            from: fromAddress,
            to: notifyEmails,
            subject: `[${row.recurring ? "RECURRING" : "ONE-TIME"}] New $${amountDollars} donation — ${donorName}`,
            html: notificationHtml,
          }),
        );
      }

      await Promise.all(emailPromises);
    } catch (emailErr) {
      console.error("[anedot webhook] email send failed", emailErr);
    }
  }

  return NextResponse.json({ received: true });
}
